### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by Basilbabyskaria** [Basilbabyskaria/VS-code_shortCuts#2]
Vs code extensions which might come in handy

**Comment by bpvcode** [comment]
Hello @Basilbabyskaria , can you assign this to me, please?

**Comment by Basilbabyskaria** [comment]
bro thank you for contributing. i am a newbie and i am still learning this. i have noticed that you are not added as a contributor of the project. which might be because you contributed via the issues tab. How can i update you as a contributor.
