### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by Wangata** [Basilbabyskaria/VS-code_shortCuts#33]
## Is your feature request related to a problem? Please describe
I was going through the ReadMe and I found out that there are some steps that are missing and a beginner might find it hard to go through the git process 
## Describe the solution you'd like
I would like to add and edit the readme to make it simple to understand and implement

**Comment by Wangata** [comment]
Also, don't forget to include the hacktoberfest tag

**Comment by lakshayanand1** [comment]
Please assign this issue to me

**Comment by Wangata** [comment]
Check PR
